<?php include ("./app/Views/Layout/header.php");?>


    <body class="text-center">

<div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="error-alert" class="toast" role="alert" aria-live="assertive" aria-atomic="true" style="background:red">
        <div class="toast-header">
            <img src="../../favicon.svg" class="rounded me-2" alt="...">
            <strong class="me-auto">Alert message</strong>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Закрыть"></button>
        </div>
        <div class="toast-body">
            <?= $_GET['error'] ?>
        </div>
    </div>
</div>

<form class="form-signin" action="<?= $url ?>/?c=login&a=login" method="post">
    <img class="mb-4" src="../../favicon.svg" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Пожалуйста, войдите</h1>
    <p><em>Нет аккаунта? <a href="<?= $url ?>/?c=register">Регистрация</a></em></p>

    <label for="inputEmail" class="sr-only">Email </label>
    <input type="email" id="inputEmail" class="form-control"
           placeholder="Email адрес" name="email" value="<?= $_SESSION['oldValue']['email'] ?? "" ?>" required autofocus>
    <br>
    <label for="inputPassword" class="sr-only">Пароль</label>
    <input type="password" id="inputPassword"
           name="password" class="form-control" placeholder="Пароль" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
</form>

<?php include ("./app/Views/Layout/footer.php");?>